// Rental agreement copy (English).
export const strings = {
  title: 'Vehicle Rental Agreement',
  agreementNo: 'Agreement No',
  date: 'Date',
  lessor: 'Lessor',
  lessee: 'Lessee',
  vehicle: 'Vehicle',
  rentalTerms: 'Rental Period',
  charges: 'Charges',
  termsTitle: 'Terms & Conditions',
  terms: [
    'The Lessee confirms they hold a valid driving licence and are legally permitted to operate the vehicle.',
    'The vehicle must be returned by the agreed return date and time; late returns incur a late fee equal to the daily rate per extra day.',
    'The security deposit is refundable on return, subject to deductions for damage, fines, or fuel shortfalls.',
    'The Lessee is responsible for all traffic violations, tolls and fines during the rental period.',
    'The vehicle shall not be sub-let, used for racing, or driven under the influence of alcohol or drugs.',
    'Any damage, accident or theft must be reported to the Lessor immediately.',
  ],
  labels: {
    mobile: 'Mobile', email: 'Email', licence: 'Licence', address: 'Address',
    registration: 'Registration', chassis: 'Chassis', pickup: 'Pickup', ret: 'Return', days: 'Days',
    pickupLoc: 'Pickup Location', dropLoc: 'Drop Location',
    dailyRate: 'Daily rate', rentSubtotal: 'Rental subtotal', lateFee: 'Late fee', securityDeposit: 'Security deposit (refundable)',
    grandTotal: 'Total payable', paid: 'Paid', balanceDue: 'Balance due',
  },
  lesseeSignature: 'Lessee Signature',
  lessorSignature: 'For Alliance Car Rental',
  signedBy: 'Signed by',
  notSigned: 'Not yet signed',
  thanks: 'Thank you for choosing Alliance Car Rental.',
};
